### ISSUE TITLE
build order

### ISSUE THREAD

**Issue by gristel** [thasmo/gulp.boilerplate#4]
Hi.
If I have

```
gulp.series(helper.values(include("some_dir/")))
```

in what order are the tasks in some_dir executed?

Thanks!

**Comment by thasmo** [comment]
Good queston. I guess it will execute the tasks in the order they're read by the helper, which is imho how the file-system returns the directories/files - probably alphabetically. That said, I've used the helper only for running tasks in parallel, not in series.

**Comment by gristel** [comment]
I find the helper quite useful for organising related tasks. I'll probably just add 01-, 02-, ... in front of the filenames then.
Thanks

**Comment by thasmo** [comment]
You're welcome. :)
