### ISSUE TITLE
-w flag not working when gulp installed locally

### ISSUE THREAD

**Issue by gristel** [thasmo/gulp.boilerplate#5]
Hi,

I don't like to install things globally, so I only install gulp locally and added a gulp run script to my package.json file.
However, when typing `npm run gulp -w`, the `-w` flag doesn't get picked up.
Any suggestions?
Thanks!

**Comment by thasmo** [comment]
@gristel, would you mind sharing your `package.json` configuration regarding the run scripts? Thanks!

**Comment by gristel** [comment]
This is the only run script I have:

```
"scripts": {
  "gulp": "./node_modules/gulp/bin/gulp.js"
}
```

**Comment by gristel** [comment]
No matter what I try, running `npm run gulp -w` always gets stuck in the

```
if (!cli.watch || gulp.lastRun(task)) {
  return
}
```

So I'm guessing the argument doesn't get passed, but I have no idea how to pass it.

**Comment by thasmo** [comment]
@gristel Does [that](http://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script) help?

**Comment by gristel** [comment]
The only thing that seems to work is run

```
npm run gulp -- -w
```

I can live with that ;-)

**Comment by thasmo** [comment]
Ye, that's the way `npm` does this, I guess.
